name: 'Kiwi: Download translations from Crowdin'

on:
  workflow_dispatch
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
      
      - name: Downloading translations
        run: php toolbox/download_translations_from_crowdin.php ${{ secrets.CROWDIN_APIKEY }}

      - name: Git auto-commit
        uses: stefanzweifel/git-auto-commit-action@v4.11.0
        with:
          # Commit message
          commit_message: Updated translation files from Crowdin
          file_pattern: chrome/android/java/res/*/
