name: Lint codebase

#############################
# Start the job on all push #
#############################
on:
  push:
    branches: [kiwi]
  pull_request:
    branches: [kiwi]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Run source-code linter
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checking-out code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Running Super-Linter
        uses: github/super-linter:slim-v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: kiwi
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
