name: Rebase on new Chromium version

on:
  workflow_dispatch:
  push:
    paths:
      - 'CHROMIUM_VERSION'

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Loading settings from CHROMIUM_VERSION
        run: |
          source CHROMIUM_VERSION; export $(cut -d= -f1 CHROMIUM_VERSION | grep -vF '#')
          env | grep -F CHROMIUM_ >> $GITHUB_ENV

      # https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/
      # git clone --filter=tree:0 <url> creates a treeless clone.
      # These clones download all reachable commits while fetching trees and blobs on-demand. These clones are best for build environments where the repository will be deleted after a single build, but you still need access to commit history
      - name: Checking out Chromium
        run: |
          git clone --filter=tree:0 --no-checkout https://github.com/chromium/chromium.git chromium
          cd chromium
          git checkout ${{ env.CHROMIUM_MAJOR }}.${{ env.CHROMIUM_MINOR }}.${{ env.CHROMIUM_BUILD }}.${{ env.CHROMIUM_PATCH }}
          git sparse-checkout set chrome/android

      - name: Listing files
        run: ls -laR
