name: Rebase on new Chromium VERSION

on:
  workflow_dispatch:
  push:
    paths:
      - 'CHROMIUM_VERSION'

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Loading CHROMIUM_VERSION config file
        run: source CHROMIUM_VERSION

      - name: Downloading files
        run: wget 'https://chromium.googlesource.com/chromium/src/+/refs/tags/$CHROMIUM_MAJOR.$CHROMIUM_MINOR.$CHROMIUM_BUILD.$CHROMIUM_PATCH/chrome/browser/resources/extensions/extensions.html?format=TEXT' -O chrome/browser/resources/extensions/extensions.html
        
      - name: Outputting file
        run: cat chrome/browser/resources/extensions/extensions.html | base64 --decode
    
