name: rebase and build APK

on:
  workflow_dispatch:
  push:
    paths:
      - 'CHROMIUM_VERSION'

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        platform: [arm, arm64, x86, x64]

    steps:
      - name: Initializing build
        run: echo Initializing build for platform ${{ matrix.platform }}

  sign_and_upload:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Installing rclone
        run: curl https://rclone.org/install.sh | sudo bash -s beta
 
