name: Rename directory

on:
  workflow_dispatch:
    inputs:
      source_directory:
        description: 'Source directory path'     
        required: true
      destination_directory:
        description: 'Destination directory path'     
        required: true

jobs:
  rename:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - run: git mv ${{ github.event.inputs.source_directory }} ${{ github.event.inputs.destination_directory }}
      
      - uses: EndBug/add-and-commit@v5.1.0
